# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_modern_controller_overhaul"

# Version of this mod.
version = "3.1.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Modern Controller Overhaul"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod aims to overhaul the HUD and UI surrounding the game's control scheme in order to align it as closely as possible with modern controllers.

It does this through repositioning HUD elements, replacing text and textures mentioning control schemes, and fixing inconsistencies and bugs with the original game.

GitHub Repository: https://github.com/t0mtee/MMRecompModernHUD
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "C-buttons? Never heard of them."

# Authors of this mod.
authors = [ "tomtee" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
    "MM_EZ_Text_Replacer_API:2.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_modern_controller_overhaul"

# Reference symbol files.
func_reference_syms_file = "mm.us.rev1.syms.toml"
data_reference_syms_files = [ "mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "custom-static-syms.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png", "textures/Nintendo/rt64.json",
                    "textures/Nintendo/rt64-low-mip-cache.bin",
                    "textures/Nintendo/32390d4efccf727b.dds",
                    "textures/Nintendo/e6c3403b9537feb1.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#218CFC10#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#ACF93890#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#E973D922#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#48D41F13#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#C090A2AC#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#8D30266D#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#C8D66332#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#844E1CE5#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#F0375507#3#1_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#90547324#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#B14134FA#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#0A7871D8#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#9C51DC08#4#0_all.dds",
                    "textures/Nintendo/ZELDA MAJORA'S MASK#986CC390#4#0_all.dds" ]

[[manifest.config_options]]
id = "glyphs"
name = "Button Glyphs"
description = """
Button Glyphs are the icons overlayed on a button when there's no item on it.

In base Majora's Mask, only the C-buttons have button glyphs, however this mod adds functionality for drawing glyphs for the A and B button.

Or you can disable them fully if you prefer a cleaner look or have a controller with a strange layout.
"""
type = "Enum"
options = [ "Disabled", "C-buttons", "All" ]
default = "All"

[[manifest.config_options]]
id = "_recomp_texture_pack_enabled"
name = "Texture Replacement"
description = """
If enabled, all texture references to C-buttons and other N64-era inputs will be changed to reflect modern Nintendo controllers, based on the default control scheme.

Make sure this mod is placed ABOVE any texture packs you may have installed if you enable this.

Uses HD textures. You can find textures for other controllers / control schemes on the Thunderstore page.

Credit to pizza1398 for designing the pause menu switcher buttons and to Nerrel and GhostlyDark for the base of most of the HD textures.

I'll happily take contributions to improve textures! Contact me on Discord (tomtee_) or open a PR on Github.
"""
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "text_replacement"
name = "Text Replacement"
description = """
If enabled, all text references to the old control scheme will be changed to reflect modern controllers.

This changes references of Z Targeting to:
- ZL Targeting for Nintendo controllers.
- LT Targeting for Xbox controllers or the ROG Ally.
- L2 Targeting for DualShock / 8BitDo controllers or the Steam Deck.

Have I missed any text? Contact me on Discord (tomtee_) or open an issue on Github.
"""
type = "Enum"
options = [ "Disabled", "ZL", "LT", "L2" ]
default = "ZL"

[[manifest.config_options]]
id = "attack_item_scale"
name = "Attack Item Scaling"
description = """
If enabled, the items equipped to the Attack button are scaled down slightly to actually fit the button and align better with the items equipped to other buttons.

When not using HD textures, this option can cause issues with the icon rendering. The shadows of some swords will be elongated.
""" 
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]
id = "shoulder_position"
name = "Shoulder Button Position"
description = """
Would you like the shoulder button to aligned with the up button or slightly lower / higher?
""" 
type = "Enum"
options = [ "Lower", "Aligned", "Higher" ]
default = "Lower"

[[manifest.config_options]]
id = "action_button"
name = "Action Button Position"
description = """
Where do you want the Action Button to be positioned?
"""
type = "Enum"
options = [ "Up", "Left", "Down", "Right", "Shoulder" ]
default = "Right"

[[manifest.config_options]]
id = "attack_button"
name = "Attack Button Position"
description = """
Where do you want the Attack Button to be positioned?
"""
type = "Enum"
options = [ "Up", "Left", "Down", "Right", "Shoulder" ]
default = "Down"

[[manifest.config_options]]
id = "1_button"
name = "C-Left Button Position"
description = """
Where do you want the C-Left Button to be positioned?
"""
type = "Enum"
options = [ "Up", "Left", "Down", "Right", "Shoulder" ]
default = "Left"

[[manifest.config_options]]
id = "2_button"
name = "C-Down Button Position"
description = """
Where do you want the C-Down Button to be positioned?
"""
type = "Enum"
options = [ "Up", "Left", "Down", "Right", "Shoulder" ]
default = "Up"

[[manifest.config_options]]
id = "3_button"
name = "C-Right Button Position"
description = """
Where do you want the C-Right Button to be positioned?
"""
type = "Enum"
options = [ "Up", "Left", "Down", "Right", "Shoulder" ]
default = "Shoulder"